# Generated by Django 5.1.1 on 2024-10-22 20:28

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('key_info', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField(default='http://localhost:9000/assets/404.png')),
                ('detail_text', models.TextField(default='There is no detail text')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'configuration_elements',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалёна'), ('created', 'Сформирована'), ('completed', 'Завершёна'), ('rejected', 'Отклонёна')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=20, null=True)),
                ('customer_email', models.CharField(max_length=255, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('plane', models.CharField(default='Global 7500', max_length=255, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='configurations_moderator_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr1_code.configuration')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr1_code.configurationelement')),
            ],
            options={
                'db_table': 'configuration_map',
                'unique_together': {('configuration', 'element')},
            },
        ),
    ]
