# Generated by Django 5.1.1 on 2024-09-20 07:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('key_info', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField(default='')),
                ('detail_text', models.TextField(default='There is no detail text')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'configuration_elements',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалёна'), ('created', 'Сформирована'), ('completed', 'Завершёна'), ('rejected', 'Отклонёна')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configurations', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plane', models.CharField(max_length=255)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr1_code.configuration')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr1_code.configurationelement')),
            ],
            options={
                'db_table': 'planes',
                'unique_together': {('configuration', 'element')},
            },
        ),
    ]
