# Generated by Django 5.1.1 on 2024-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
