# Generated by Django 5.1.1 on 2024-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationelement',
            name='image',
            field=models.URLField(default='http://localhost:9000/assets/404.png', null=True),
        ),
    ]
