# Generated by Django 5.1.1 on 2024-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0002_configuration_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='plane',
            field=models.CharField(default='Global 7500', max_length=255),
        ),
    ]
