# Generated by Django 5.1.1 on 2024-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0003_alter_plane_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='customer_email',
            field=models.CharField(max_length=255),
        ),
    ]
