# Generated by Django 5.1.1 on 2024-09-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0004_alter_configuration_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='plane',
            field=models.CharField(default='Global 7500', max_length=255),
        ),
        migrations.CreateModel(
            name='ConfigurationMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(max_length=255)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr1_code.configuration')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr1_code.configurationelement')),
            ],
            options={
                'db_table': 'configuration_map',
                'unique_together': {('configuration', 'element')},
            },
        ),
        migrations.DeleteModel(
            name='Plane',
        ),
    ]
