# Generated by Django 5.1.1 on 2024-10-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0007_authuser_alter_configuration_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
