# Generated by Django 5.1.1 on 2024-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr1_code', '0008_alter_configuration_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationelement',
            name='image',
            field=models.URLField(default='http://localhost:9000/assets/404.png'),
        ),
    ]
